# Generated by Django 5.2.17 on 2026-08-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pinned to the last migration shipped by pretix itself. makemigrations
        # tends to invent a fresh pretixbase migration for locale choices, which
        # only exists inside the container it ran in; depending on that would
        # break every other install.
        ('pretixbase', '0306_alter_eventmetaproperty_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openpos_prices', to='pretixbase.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openpos_prices', to='pretixbase.item')),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openpos_prices', to='pretixbase.itemvariation')),
            ],
            options={
                'verbose_name': 'On-site price',
                'verbose_name_plural': 'On-site prices',
                'constraints': [models.UniqueConstraint(condition=models.Q(('variation__isnull', False)), fields=('item', 'variation'), name='openpos_price_unique_variation'), models.UniqueConstraint(condition=models.Q(('variation__isnull', True)), fields=('item',), name='openpos_price_unique_item')],
            },
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(db_index=True)),
                ('device_serial', models.CharField(max_length=190)),
                ('cashier', models.CharField(max_length=190)),
                ('order_code', models.CharField(max_length=16)),
                ('payment_type', models.CharField(max_length=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('cash_given', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('cash_change', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('positions', models.JSONField(default=list)),
                ('idempotency_key', models.CharField(max_length=190)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openpos_sales', to='pretixbase.device')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openpos_sales', to='pretixbase.event')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openpos_sales', to='pretixbase.order')),
            ],
            options={
                'verbose_name': 'Till sale',
                'verbose_name_plural': 'Till sales',
                'ordering': ('event', 'seq'),
                'constraints': [models.UniqueConstraint(fields=('event', 'seq'), name='openpos_sale_unique_seq'), models.UniqueConstraint(fields=('event', 'idempotency_key'), name='openpos_sale_unique_idempotency')],
            },
        ),
    ]
