"""
Talking to SumUp.

Everything this plugin sends to SumUp goes through here, and nothing else
imports ``requests``. That is worth a module of its own for three reasons: the
API key must never reach a log, a template or the till; every call needs a
timeout, because a card reader that has gone quiet must not hold a gunicorn
worker until it gives up; and the shape of a failure matters more than usual —
"the reader said no" and "we could not reach SumUp" lead to different words in
front of a customer.

**The webhook is never believed.** SumUp's reader callback carries no signature
(see ``ReaderCheckoutStatusChange`` in their OpenAPI description: an event id, a
client transaction id, a merchant code and a status, and nothing to
authenticate any of it). Anyone who can reach the URL could post "successful".
So the callback is treated as a nudge and nothing more: it makes the server go
and ask the Transactions API what really happened. Polling does the same thing
on a timer, which is what makes the callback optional — a pretix that SumUp
cannot reach still settles every payment, just a second or two later.

The API this speaks to, all of it under https://api.sumup.com:

* ``POST /v0.1/merchants/{m}/readers/{r}/checkout`` — start a payment. Answers
  with a ``client_transaction_id`` *generated by SumUp*, which is the only
  handle we get on the transaction until it exists, and a ``checkout_id`` for
  the request itself.
* ``GET  /v0.1/merchants/{m}/readers/{r}/checkout/{checkout_id}`` — what became
  of that request, which is the one thing that knows before any card has been
  presented: cancelled, expired, or still waiting.
* ``POST /v0.1/merchants/{m}/readers/{r}/terminate`` — stop one that is still
  waiting for the cardholder.
* ``GET  /v2.1/merchants/{m}/transactions?client_transaction_id=…`` — what
  actually happened, and the transaction ``id`` a refund needs.
* ``POST /v1.0/merchants/{m}/payments/{id}/refunds`` — refund, in full or part.
* ``GET/POST/DELETE /v0.1/merchants/{m}/readers`` — the paired readers.
"""
import logging
from decimal import Decimal

import requests
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)

API_BASE = "https://api.sumup.com"

#: Connect and read timeouts, in seconds.
#:
#: Generous on read because the checkout call is answered by SumUp's own
#: infrastructure rather than by the reader — the reader is reached
#: asynchronously afterwards — but still bounded: every one of these calls
#: happens with somebody standing at a counter.
TIMEOUT = (5, 15)

#: Transaction statuses that mean the customer's money moved.
#:
#: ``PAID_OUT`` is a successful payment that has since been settled to the
#: merchant, which a till looking at an old sale will see. ``REFUNDED`` is
#: deliberately absent: the money moved and then moved back, and a sale must
#: not be booked against it.
SUCCEEDED = frozenset({"SUCCESSFUL", "PAID_OUT"})
#: Still going. Anything else is a refusal, a cancellation or a fault.
PENDING = frozenset({"PENDING"})


#: What went wrong, as something code may branch on.
#:
#: The messages beside these are for an operator to read, which means they are
#: translated, which means they are the one thing a caller must never test.
#: ``transaction()`` did exactly that once: it recognised "the transaction does
#: not exist yet" — the *normal* state while a cardholder has not tapped — by
#: looking for an English phrase inside the message. A French catalogue would
#: have turned every reader payment into a refusal two seconds after it
#: started. Codes are here so that can never come back.
ERR_NOT_CONFIGURED = "not_configured"
ERR_UNAUTHORIZED = "unauthorized"
ERR_NOT_FOUND = "not_found"
ERR_BUSY = "busy"
ERR_OFFLINE = "offline"
ERR_UNAVAILABLE = "unavailable"
ERR_UNREADABLE = "unreadable"
ERR_REFUSED = "refused"


class SumUpError(Exception):
    """
    A call to SumUp did not do what was asked.

    ``message`` is safe to show an operator: it never carries the key, and it
    says what to do rather than what HTTP status came back. ``code`` is the
    same fact for a caller, and it is the half that stays stable under
    translation.
    """

    def __init__(self, message, *, code=ERR_REFUSED, retryable=False, detail="", reason=""):
        super().__init__(detail or message)
        self.message = message
        #: One of the ``ERR_*`` constants above. Branch on this, never on
        #: ``message``, which is translated.
        self.code = code
        #: Whether trying the same thing again could plausibly work.
        self.retryable = retryable
        #: For the log. May carry SumUp's own wording; never the credentials.
        self.detail = detail
        #: What SumUp said, in its own words and short: the status, then its
        #: explanation. Empty when SumUp was never reached. For the back office
        #: only — see :meth:`explained` — never for the till's screen.
        self.reason = reason

    def explained(self):
        """
        The message, followed by SumUp's own words when there are some.

        For the back office, where the person reading is reconciling money and
        has to tell a key that may not refund from a transaction SumUp will not
        refund yet. SumUp's own dashboard, refusing the same refund, says
        neither. The till keeps the plain message: a volunteer at a counter can
        act on "take it in cash", not on an HTTP status.
        """
        if not self.reason:
            return str(self.message)
        return str(_("{message} SumUp answered: {reason}").format(
            message=self.message, reason=self.reason
        ))


class SumUpAccount:
    """
    The organizer's SumUp credentials, and the calls they authorise.

    Built from organizer settings rather than event settings: a card reader
    belongs to the association, not to the evening it is used at, and the
    devices it is attached to are organizer-level too.
    """

    def __init__(self, organizer):
        self.organizer = organizer
        settings = organizer.settings
        self.merchant_code = (settings.get("openpos_sumup_merchant_code") or "").strip()
        # Read but never exposed: no property, no repr, and nothing that
        # renders an object of this class may reach a template.
        self._api_key = (settings.get("openpos_sumup_api_key") or "").strip()

    def __repr__(self):  # pragma: no cover - debugging aid, never in output
        return f"<SumUpAccount {self.organizer.slug} configured={self.configured}>"

    @property
    def configured(self) -> bool:
        return bool(self.merchant_code and self._api_key)

    # -- plumbing ----------------------------------------------------------

    def _call(
        self, method, path, *, json=None, params=None, expect=(200, 201, 204),
        timeout=None,
    ):
        if not self.configured:
            raise SumUpError(
                _("SumUp is not set up for this organizer yet."),
                code=ERR_NOT_CONFIGURED,
                detail="missing merchant code or API key",
            )
        url = f"{API_BASE}{path}"
        try:
            response = requests.request(
                method,
                url,
                json=json,
                params=params,
                headers={
                    "Authorization": f"Bearer {self._api_key}",
                    "Accept": "application/json",
                },
                timeout=timeout or TIMEOUT,
            )
        except requests.RequestException as exc:
            # Includes both timeouts and DNS/TLS failures. Retryable: the till
            # is being told to try again, not that the payment failed — which
            # is a distinction the operator has to be able to act on.
            logger.warning("SumUp %s %s could not be reached: %s", method, path, exc)
            raise SumUpError(
                _("SumUp could not be reached. Check the connection and try again."),
                code=ERR_UNAVAILABLE,
                retryable=True,
                detail=str(exc),
            ) from exc

        if response.status_code in expect:
            if response.status_code == 204 or not response.content:
                return {}
            try:
                return response.json()
            except ValueError as exc:
                raise SumUpError(
                    _("SumUp sent an answer this till could not read."),
                    code=ERR_UNREADABLE,
                    detail=response.text[:500],
                ) from exc

        raise self._error_for(method, path, response)

    def _error_for(self, method, path, response):
        detail = response.text[:500]
        logger.warning(
            "SumUp %s %s answered %s: %s", method, path, response.status_code, detail
        )
        # SumUp's answer never repeats the key it was sent, but this is the
        # one string built from it that is meant to be shown, so it is made
        # sure of rather than assumed.
        reason = _explanation(response)
        if self._api_key:
            reason = reason.replace(self._api_key, "…")
        # The two refusals a counter actually meets, which SumUp names in the
        # body of a 422 rather than with a status of their own. Neither is
        # retryable in this module's sense: the amount was *not* put on the
        # reader, so the payment has failed rather than become unknown — the
        # cashier tries again once the reader is back, or takes cash.
        kind = _error_type(response)
        if kind == "READER_OFFLINE":
            return SumUpError(
                _("The card reader is offline. Check that it is switched on and "
                  "connected, then try again."),
                code=ERR_OFFLINE,
                detail=detail,
                reason=reason,
            )
        if kind == "READER_BUSY":
            # SumUp holds a reader for a minute after every request it accepts,
            # whether or not a card ever came near it. The usual cause is this
            # very counter: a payment stopped, and another started at once.
            return SumUpError(
                _("The card reader is still busy with the previous request. Try "
                  "again in a minute."),
                code=ERR_BUSY,
                detail=detail,
                reason=reason,
            )
        if response.status_code in (401, 403):
            return SumUpError(
                _("SumUp refused the API key. Check it in the Open POS settings."),
                code=ERR_UNAUTHORIZED,
                detail=detail,
                reason=reason,
            )
        if response.status_code == 404:
            return SumUpError(
                _("SumUp does not know this reader or transaction."),
                code=ERR_NOT_FOUND,
                detail=detail,
                reason=reason,
            )
        if response.status_code >= 500:
            return SumUpError(
                _("SumUp is having trouble. Try again in a moment."),
                code=ERR_UNAVAILABLE,
                retryable=True,
                detail=detail,
                reason=reason,
            )
        return SumUpError(
            # The body may name the field that was wrong, which is the one
            # thing worth passing on; it is SumUp's own text, so it stays off
            # the till's screen and goes to the log, and to the back office as
            # ``reason``.
            _("SumUp refused this request."),
            detail=detail,
            reason=reason,
        )

    # -- readers -----------------------------------------------------------

    def readers(self):
        """Every reader paired to this merchant account."""
        body = self._call("GET", f"/v0.1/merchants/{self.merchant_code}/readers")
        return body.get("items", []) if isinstance(body, dict) else []

    def pair_reader(self, pairing_code, name):
        """
        Claim the reader showing ``pairing_code``.

        The answer comes back ``processing``: the physical device has to
        acknowledge, which it does within a few seconds. The back office says
        so rather than pretending the reader is ready.
        """
        return self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers",
            json={"pairing_code": pairing_code, "name": name},
        )

    def forget_reader(self, reader_id):
        self._call(
            "DELETE",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}",
            expect=(200, 204),
        )

    #: What a reader says it is doing, when it is doing something.
    #:
    #: SumUp's own vocabulary, kept as it comes: turning these into words for
    #: an operator is the template's job, and inventing a state here that
    #: SumUp did not send would be worse than showing the raw one.
    STATE_IDLE = "IDLE"
    STATE_UPDATING = "UPDATING_FIRMWARE"
    BUSY_STATES = (
        "SELECTING_TIP",
        "WAITING_FOR_CARD",
        "WAITING_FOR_PIN",
        "WAITING_FOR_SIGNATURE",
    )

    def reader_status(self, reader_id, *, timeout=(5, 5)):
        """
        Whether a reader is reachable, and what it is doing right now.

        Answers ``{"status": "ONLINE"|"OFFLINE", "state": ..., "battery_level":
        ..., "firmware_version": ..., "last_activity": ...}`` — what SumUp sends
        under ``data`` — or ``None`` when this reader cannot say. Two reasons it
        cannot, and neither is a fault: the endpoint needs firmware 3.3.39.0 on
        a Solo — a reader old enough to take payments but not old enough to be
        asked about them — and SumUp may simply not answer in time.

        Bounded harder than the rest of the API on purpose. This is called to
        draw a back-office page, one call per reader, and a reader that has
        gone quiet must not hold that page for fifteen seconds to tell us so:
        not knowing, quickly, is the more useful answer.
        """
        try:
            body = self._call(
                "GET",
                f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}/status",
                timeout=timeout,
            )
        except SumUpError as exc:
            logger.info(
                "SumUp would not say what reader %s is doing: %s", reader_id, exc.code
            )
            return None
        # Under ``data``, like the rest of the Readers API. Looked for at the
        # top level, it was never found: every reader read as "unknown" on the
        # back office, switched on and online or not.
        data = body.get("data") if isinstance(body, dict) else None
        if not isinstance(data, dict) or not data.get("status"):
            return None
        return data

    # -- payments ----------------------------------------------------------

    def start_checkout(self, reader_id, *, amount, currency, description, return_url=None):
        """
        Put an amount on a reader and let the cardholder answer it.

        Returns SumUp's ``client_transaction_id``, which is the only handle on
        this payment until a transaction exists to look up, and the
        ``checkout_id`` of the request — empty if SumUp leaves it out, which its
        description allows. Note what is *not* sent: an idempotency key. This
        endpoint has none — retrying it starts a second payment — so the caller
        must not retry blindly, and the journal's own key is what stops one
        basket becoming two sales.
        """
        body = self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}/checkout",
            json={
                "total_amount": {
                    "currency": currency,
                    "minor_unit": 2,
                    "value": minor_units(amount),
                },
                "description": description,
                **({"return_url": return_url} if return_url else {}),
            },
            expect=(200, 201),
        )
        data = body.get("data") or {}
        client_transaction_id = data.get("client_transaction_id")
        if not client_transaction_id:
            raise SumUpError(
                _("SumUp accepted the payment but named no transaction."),
                detail=str(body)[:500],
            )
        return client_transaction_id, str(data.get("checkout_id") or "")

    def reader_checkout(self, reader_id, checkout_id):
        """
        What became of a payment request put on a reader, or ``None``.

        The Transactions API has nothing to say until a card has been
        presented, so on its own it cannot tell "the customer is still looking
        for their card" from "the cashier pressed stop" or "the customer left".
        This can: SumUp keeps the request itself, with a status of ``pending``,
        ``successful``, ``failed`` or ``cancelled``, and cancels it by itself
        once it expires.

        ``None`` whenever it cannot say, for any reason — this is asked only to
        close a payment early, and not knowing leaves it exactly as it was.
        """
        try:
            body = self._call(
                "GET",
                f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}"
                f"/checkout/{checkout_id}",
            )
        except SumUpError as exc:
            logger.info(
                "SumUp would not say what became of checkout %s: %s",
                checkout_id, exc.code,
            )
            return None
        data = body.get("data") if isinstance(body, dict) else None
        if not isinstance(data, dict) or not data.get("status"):
            return None
        return data

    def terminate_checkout(self, reader_id):
        """
        Stop a payment the reader is still waiting on.

        Best-effort by design: SumUp says there is no confirmation, and the
        device must be online and still waiting for the cardholder. The caller
        settles what actually happened by asking for the transaction.
        """
        self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}/terminate",
            expect=(200, 202, 204),
        )

    def transaction(self, client_transaction_id):
        """
        What SumUp says about a payment, or ``None`` while it does not exist.

        A reader checkout that has been accepted but not yet answered by the
        cardholder has no transaction, and SumUp says so with a 404. That is
        not an error here: it is "still waiting", which is exactly what the
        till is asking about.

        Looked up by the ``client_transaction_id`` the reader checkout
        returned, because that is the only handle there is until a transaction
        exists. The transaction's own id comes back in the answer, and is what
        a refund later points at.
        """
        try:
            return self._call(
                "GET",
                f"/v2.1/merchants/{self.merchant_code}/transactions",
                params={"client_transaction_id": client_transaction_id},
            )
        except SumUpError as exc:
            # Not yet answered by the cardholder: SumUp has no transaction to
            # show until the card is presented, and says so with a 404. Matched
            # on the code, never on the message — see ERR_NOT_FOUND above.
            if exc.code == ERR_NOT_FOUND:
                return None
            raise

    def refund(self, transaction_id, amount=None):
        """
        Give the money back, in full or in part.

        There is exactly one refund route in SumUp's API and it takes a
        transaction in its URL: the amount "can't exceed the amount of the
        transaction", and there is no way to send money to a card that no
        transaction stands behind. That is why a returned cup deposit is paid
        out of the drawer and not onto a card — see the deposit section of
        docs/fonctionnement.md.
        """
        self._call(
            "POST",
            f"/v1.0/merchants/{self.merchant_code}/payments/{transaction_id}/refunds",
            # An empty object for the whole transaction, never no body at all.
            # The spec calls the body optional, but SumUp's own client
            # (sumup-go, ``TransactionsClient.Refund``) always sends one, as
            # JSON: that is the request SumUp is known to take. Without an
            # amount, SumUp refunds the transaction in full.
            json=({"amount": float(amount)} if amount is not None else {}),
            # 201 is what SumUp answers a refund with. Left out, every refund
            # that went through was reported as refused: the operator told to
            # refund from the SumUp app a card that had already been paid back.
            expect=(200, 201, 204),
        )


def _error_type(response):
    """
    SumUp's own name for what went wrong, where it gives one.

    The Readers API answers ``{"errors": {"type": "READER_BUSY", "detail":
    ...}}``; other routes answer with a problem document, or a map of field
    names to complaints, and have no such name.
    """
    try:
        body = response.json()
    except ValueError:
        return None
    errors = body.get("errors") if isinstance(body, dict) else None
    kind = errors.get("type") if isinstance(errors, dict) else None
    return kind if isinstance(kind, str) else None


def _explanation(response):
    """
    What SumUp said, in its own words, short enough to show an organizer.

    The status comes first: a 403 and a 409 are different people's problems,
    the key's and the transaction's. Then whatever wording SumUp gave, which it
    puts in a different place on nearly every route — a problem document's
    ``detail``, the Readers API's ``errors`` object, a list of ``errors`` each
    with a ``code``, an older ``error_code`` and ``message``, a map of field
    names to complaints. Anything that is not text is left out, and an answer
    that is not JSON at all, a proxy's error page, leaves the status alone.
    """
    try:
        body = response.json()
    except ValueError:
        body = None
    if isinstance(body, list):
        body = body[0] if body and isinstance(body[0], dict) else None
    words = []
    if isinstance(body, dict):
        words += [
            body.get("error_code"),
            body.get("detail") or body.get("message") or body.get("title"),
        ]
        errors = body.get("errors")
        if isinstance(errors, list):
            errors = errors[0] if errors and isinstance(errors[0], dict) else None
        if isinstance(errors, dict):
            named = [
                errors.get("code") or errors.get("type"),
                errors.get("detail") or errors.get("message"),
            ]
            if not any(isinstance(word, str) for word in named):
                # A field and what is wrong with it, as SumUp's validation
                # answers put it: {"total_amount": ["must be greater than 0"]}.
                field, complaint = next(iter(errors.items()), (None, None))
                if isinstance(complaint, list) and complaint:
                    complaint = complaint[0]
                if isinstance(field, str) and isinstance(complaint, str):
                    named = [f"{field}: {complaint}"]
            words += named
    parts = [str(response.status_code)]
    for word in words:
        if isinstance(word, str) and word.strip() and word.strip() not in parts:
            parts.append(word.strip())
    return " · ".join(parts)[:190]


#: How a reader checkout ends without anybody being charged.
CHECKOUT_CLOSED = frozenset({"failed", "cancelled"})


def minor_units(amount: Decimal) -> int:
    """
    A decimal amount as the integer SumUp wants, for a two-decimal currency.

    Quantised rather than truncated, and via Decimal rather than float: a
    binary float of 20.15 is 20.149999…, and int() of that is a cent short on
    somebody's card.
    """
    return int((Decimal(amount).quantize(Decimal("0.01")) * 100).to_integral_value())


def succeeded(transaction) -> bool:
    return bool(transaction) and transaction.get("status") in SUCCEEDED


def still_running(transaction) -> bool:
    """
    Whether it is worth asking again.

    A transaction that does not exist yet counts: the cardholder has not
    answered the reader.
    """
    return transaction is None or transaction.get("status") in PENDING
