"""
Talking to SumUp.

Everything this plugin sends to SumUp goes through here, and nothing else
imports ``requests``. That is worth a module of its own for three reasons: the
API key must never reach a log, a template or the till; every call needs a
timeout, because a card reader that has gone quiet must not hold a gunicorn
worker until it gives up; and the shape of a failure matters more than usual —
"the reader said no" and "we could not reach SumUp" lead to different words in
front of a customer.

**The webhook is never believed.** SumUp's reader callback carries no signature
(see ``ReaderCheckoutStatusChange`` in their OpenAPI description: an event id, a
client transaction id, a merchant code and a status, and nothing to
authenticate any of it). Anyone who can reach the URL could post "successful".
So the callback is treated as a nudge and nothing more: it makes the server go
and ask the Transactions API what really happened. Polling does the same thing
on a timer, which is what makes the callback optional — a pretix that SumUp
cannot reach still settles every payment, just a second or two later.

The API this speaks to, all of it under https://api.sumup.com:

* ``POST /v0.1/merchants/{m}/readers/{r}/checkout`` — start a payment. Answers
  with a ``client_transaction_id`` *generated by SumUp*, which is the only
  handle we get on the transaction until it exists.
* ``POST /v0.1/merchants/{m}/readers/{r}/terminate`` — stop one that is still
  waiting for the cardholder.
* ``GET  /v2.1/merchants/{m}/transactions?client_transaction_id=…`` — what
  actually happened, and the transaction ``id`` a refund needs.
* ``POST /v1.0/merchants/{m}/payments/{id}/refunds`` — refund, in full or part.
* ``GET/POST/DELETE /v0.1/merchants/{m}/readers`` — the paired readers.
"""
import logging
from decimal import Decimal

import requests
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)

API_BASE = "https://api.sumup.com"

#: Connect and read timeouts, in seconds.
#:
#: Generous on read because the checkout call is answered by SumUp's own
#: infrastructure rather than by the reader — the reader is reached
#: asynchronously afterwards — but still bounded: every one of these calls
#: happens with somebody standing at a counter.
TIMEOUT = (5, 15)

#: Transaction statuses that mean the customer's money moved.
#:
#: ``PAID_OUT`` is a successful payment that has since been settled to the
#: merchant, which a till looking at an old sale will see. ``REFUNDED`` is
#: deliberately absent: the money moved and then moved back, and a sale must
#: not be booked against it.
SUCCEEDED = frozenset({"SUCCESSFUL", "PAID_OUT"})
#: Still going. Anything else is a refusal, a cancellation or a fault.
PENDING = frozenset({"PENDING"})


#: What went wrong, as something code may branch on.
#:
#: The messages beside these are for an operator to read, which means they are
#: translated, which means they are the one thing a caller must never test.
#: ``transaction()`` did exactly that once: it recognised "the transaction does
#: not exist yet" — the *normal* state while a cardholder has not tapped — by
#: looking for an English phrase inside the message. A French catalogue would
#: have turned every reader payment into a refusal two seconds after it
#: started. Codes are here so that can never come back.
ERR_NOT_CONFIGURED = "not_configured"
ERR_UNAUTHORIZED = "unauthorized"
ERR_NOT_FOUND = "not_found"
ERR_BUSY = "busy"
ERR_UNAVAILABLE = "unavailable"
ERR_UNREADABLE = "unreadable"
ERR_REFUSED = "refused"


class SumUpError(Exception):
    """
    A call to SumUp did not do what was asked.

    ``message`` is safe to show an operator: it never carries the key, and it
    says what to do rather than what HTTP status came back. ``code`` is the
    same fact for a caller, and it is the half that stays stable under
    translation.
    """

    def __init__(self, message, *, code=ERR_REFUSED, retryable=False, detail=""):
        super().__init__(detail or message)
        self.message = message
        #: One of the ``ERR_*`` constants above. Branch on this, never on
        #: ``message``, which is translated.
        self.code = code
        #: Whether trying the same thing again could plausibly work.
        self.retryable = retryable
        #: For the log. May carry SumUp's own wording; never the credentials.
        self.detail = detail


class SumUpAccount:
    """
    The organizer's SumUp credentials, and the calls they authorise.

    Built from organizer settings rather than event settings: a card reader
    belongs to the association, not to the evening it is used at, and the
    devices it is attached to are organizer-level too.
    """

    def __init__(self, organizer):
        self.organizer = organizer
        settings = organizer.settings
        self.merchant_code = (settings.get("openpos_sumup_merchant_code") or "").strip()
        # Read but never exposed: no property, no repr, and nothing that
        # renders an object of this class may reach a template.
        self._api_key = (settings.get("openpos_sumup_api_key") or "").strip()

    def __repr__(self):  # pragma: no cover - debugging aid, never in output
        return f"<SumUpAccount {self.organizer.slug} configured={self.configured}>"

    @property
    def configured(self) -> bool:
        return bool(self.merchant_code and self._api_key)

    # -- plumbing ----------------------------------------------------------

    def _call(self, method, path, *, json=None, params=None, expect=(200, 201, 204)):
        if not self.configured:
            raise SumUpError(
                _("SumUp is not set up for this organizer yet."),
                code=ERR_NOT_CONFIGURED,
                detail="missing merchant code or API key",
            )
        url = f"{API_BASE}{path}"
        try:
            response = requests.request(
                method,
                url,
                json=json,
                params=params,
                headers={
                    "Authorization": f"Bearer {self._api_key}",
                    "Accept": "application/json",
                },
                timeout=TIMEOUT,
            )
        except requests.RequestException as exc:
            # Includes both timeouts and DNS/TLS failures. Retryable: the till
            # is being told to try again, not that the payment failed — which
            # is a distinction the operator has to be able to act on.
            logger.warning("SumUp %s %s could not be reached: %s", method, path, exc)
            raise SumUpError(
                _("SumUp could not be reached. Check the connection and try again."),
                code=ERR_UNAVAILABLE,
                retryable=True,
                detail=str(exc),
            ) from exc

        if response.status_code in expect:
            if response.status_code == 204 or not response.content:
                return {}
            try:
                return response.json()
            except ValueError as exc:
                raise SumUpError(
                    _("SumUp sent an answer this till could not read."),
                    code=ERR_UNREADABLE,
                    detail=response.text[:500],
                ) from exc

        raise self._error_for(method, path, response)

    def _error_for(self, method, path, response):
        detail = response.text[:500]
        logger.warning(
            "SumUp %s %s answered %s: %s", method, path, response.status_code, detail
        )
        if response.status_code in (401, 403):
            return SumUpError(
                _("SumUp refused the API key. Check it in the Open POS settings."),
                code=ERR_UNAUTHORIZED,
                detail=detail,
            )
        if response.status_code == 404:
            return SumUpError(
                _("SumUp does not know this reader or transaction."),
                code=ERR_NOT_FOUND,
                detail=detail,
            )
        if response.status_code == 409:
            return SumUpError(
                _("The reader is busy with another payment."),
                code=ERR_BUSY,
                retryable=True,
                detail=detail,
            )
        if response.status_code >= 500:
            return SumUpError(
                _("SumUp is having trouble. Try again in a moment."),
                code=ERR_UNAVAILABLE,
                retryable=True,
                detail=detail,
            )
        return SumUpError(
            # The body may name the field that was wrong, which is the one
            # thing worth passing on; it is SumUp's own text and stays in the
            # log rather than on the screen.
            _("SumUp refused this request."),
            detail=detail,
        )

    # -- readers -----------------------------------------------------------

    def readers(self):
        """Every reader paired to this merchant account."""
        body = self._call("GET", f"/v0.1/merchants/{self.merchant_code}/readers")
        return body.get("items", []) if isinstance(body, dict) else []

    def pair_reader(self, pairing_code, name):
        """
        Claim the reader showing ``pairing_code``.

        The answer comes back ``processing``: the physical device has to
        acknowledge, which it does within a few seconds. The back office says
        so rather than pretending the reader is ready.
        """
        return self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers",
            json={"pairing_code": pairing_code, "name": name},
        )

    def forget_reader(self, reader_id):
        self._call(
            "DELETE",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}",
            expect=(200, 204),
        )

    # -- payments ----------------------------------------------------------

    def start_checkout(self, reader_id, *, amount, currency, description, return_url=None):
        """
        Put an amount on a reader and let the cardholder answer it.

        Returns SumUp's ``client_transaction_id``, which is the only handle on
        this payment until a transaction exists to look up. Note what is *not*
        sent: an idempotency key. This endpoint has none — retrying it starts a
        second payment — so the caller must not retry blindly, and the journal's
        own key is what stops one basket becoming two sales.
        """
        body = self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}/checkout",
            json={
                "total_amount": {
                    "currency": currency,
                    "minor_unit": 2,
                    "value": minor_units(amount),
                },
                "description": description,
                **({"return_url": return_url} if return_url else {}),
            },
            expect=(200, 201),
        )
        data = body.get("data") or {}
        client_transaction_id = data.get("client_transaction_id")
        if not client_transaction_id:
            raise SumUpError(
                _("SumUp accepted the payment but named no transaction."),
                detail=str(body)[:500],
            )
        return client_transaction_id

    def terminate_checkout(self, reader_id):
        """
        Stop a payment the reader is still waiting on.

        Best-effort by design: SumUp says there is no confirmation, and the
        device must be online and still waiting for the cardholder. The caller
        settles what actually happened by asking for the transaction.
        """
        self._call(
            "POST",
            f"/v0.1/merchants/{self.merchant_code}/readers/{reader_id}/terminate",
            expect=(200, 202, 204),
        )

    def transaction(self, client_transaction_id):
        """
        What SumUp says about a payment, or ``None`` while it does not exist.

        A reader checkout that has been accepted but not yet answered by the
        cardholder has no transaction, and SumUp says so with a 404. That is
        not an error here: it is "still waiting", which is exactly what the
        till is asking about.

        Looked up by the ``client_transaction_id`` the reader checkout
        returned, because that is the only handle there is until a transaction
        exists. The transaction's own id comes back in the answer, and is what
        a refund later points at.
        """
        try:
            return self._call(
                "GET",
                f"/v2.1/merchants/{self.merchant_code}/transactions",
                params={"client_transaction_id": client_transaction_id},
            )
        except SumUpError as exc:
            # Not yet answered by the cardholder: SumUp has no transaction to
            # show until the card is presented, and says so with a 404. Matched
            # on the code, never on the message — see ERR_NOT_FOUND above.
            if exc.code == ERR_NOT_FOUND:
                return None
            raise

    def refund(self, transaction_id, amount=None):
        """
        Give the money back, in full or in part.

        There is exactly one refund route in SumUp's API and it takes a
        transaction in its URL: the amount "can't exceed the amount of the
        transaction", and there is no way to send money to a card that no
        transaction stands behind. That is why a returned cup deposit is paid
        out of the drawer and not onto a card — see the deposit section of
        docs/fonctionnement.md.
        """
        self._call(
            "POST",
            f"/v1.0/merchants/{self.merchant_code}/payments/{transaction_id}/refunds",
            json=({"amount": float(amount)} if amount is not None else None),
            expect=(200, 204),
        )


def minor_units(amount: Decimal) -> int:
    """
    A decimal amount as the integer SumUp wants, for a two-decimal currency.

    Quantised rather than truncated, and via Decimal rather than float: a
    binary float of 20.15 is 20.149999…, and int() of that is a cent short on
    somebody's card.
    """
    return int((Decimal(amount).quantize(Decimal("0.01")) * 100).to_integral_value())


def succeeded(transaction) -> bool:
    return bool(transaction) and transaction.get("status") in SUCCEEDED


def still_running(transaction) -> bool:
    """
    Whether it is worth asking again.

    A transaction that does not exist yet counts: the cardholder has not
    answered the reader.
    """
    return transaction is None or transaction.get("status") in PENDING
