from decimal import Decimal

from django.utils.translation import gettext_lazy as _
from rest_framework import serializers

from ..models import PosSale

#: Guard against a runaway client turning one tap into a thousand-line order.
MAX_LINES = 100


class CheckoutPositionSerializer(serializers.Serializer):
    item = serializers.IntegerField()
    variation = serializers.IntegerField(required=False, allow_null=True, default=None)
    count = serializers.IntegerField(min_value=1, max_value=999)


class CheckoutSerializer(serializers.Serializer):
    """
    Note what this deliberately does *not* accept: a price.

    The till only ever names products and quantities. Prices are resolved
    server-side from the on-site tariff, so a tampered-with or simply outdated
    app cannot sell a 40 EUR ticket for 4 EUR.
    """

    #: Generated by the app before its first attempt and reused for every retry,
    #: so a flaky network or a double tap cannot sell the same tickets twice.
    idempotency_key = serializers.CharField(max_length=190, min_length=8)
    positions = serializers.ListField(
        child=CheckoutPositionSerializer(), allow_empty=False, max_length=MAX_LINES
    )
    payment_type = serializers.ChoiceField(choices=[c[0] for c in PosSale.PAYMENT_CHOICES])
    cash_given = serializers.DecimalField(
        max_digits=13, decimal_places=2, required=False, allow_null=True, default=None
    )
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )
    #: What the till showed the customer.
    #:
    #: The server is the price authority, which means it can silently charge
    #: something other than the amount the operator just read out — after a
    #: price change in the backend, or a catalogue refreshed mid-basket. Sending
    #: the expected figure turns that into a refusal before any money moves.
    expected_total = serializers.DecimalField(
        max_digits=13, decimal_places=2, required=False, allow_null=True, default=None
    )

    def validate(self, data):
        cash_given = data.get("cash_given")
        if data["payment_type"] == PosSale.PAYMENT_CASH:
            if cash_given is not None and cash_given < Decimal("0.00"):
                raise serializers.ValidationError(
                    {"cash_given": _("The amount received cannot be negative.")}
                )
        elif cash_given is not None:
            raise serializers.ValidationError(
                {"cash_given": _("The amount received only applies to cash payments.")}
            )
        return data
