from datetime import timedelta
from decimal import Decimal

from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from rest_framework import serializers

from ..models import PosSale

#: Guard against a runaway client turning one tap into a thousand-line order.
MAX_LINES = 100


#: How stale a queued sale may be before it looks like a mistake rather than a
#: dropout. A night is hours; a week is somebody replaying an old backup.
MAX_OFFLINE_AGE = timedelta(days=7)


class CheckoutPositionSerializer(serializers.Serializer):
    item = serializers.IntegerField()
    variation = serializers.IntegerField(required=False, allow_null=True, default=None)
    count = serializers.IntegerField(min_value=1, max_value=999)
    #: Read for a sale recorded offline (see OfflineSerializer), and for a
    #: free-amount line, which is the one thing the till is allowed to price.
    price = serializers.DecimalField(
        max_digits=13, decimal_places=2, required=False, allow_null=True, default=None
    )
    #: Why this line costs what it costs, typed by the cashier.
    #:
    #: Its presence is what marks a line as a free amount. Required on one,
    #: because a line whose price came from the till and whose reason is blank
    #: is exactly the row nobody can account for afterwards.
    description = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )
    #: A deposit handed back rather than taken. The amount is the configured
    #: deposit product's own price, negated by the server — the till names the
    #: product and the quantity, as it does for everything else.
    refund = serializers.BooleanField(required=False, default=False)


class OfflineSerializer(serializers.Serializer):
    """
    Marks a sale that was rung up on a till with no network.

    Its presence is what unlocks client-sent prices, and it is the only thing
    that ever does. The till had no way to ask the server what a product cost:
    it charged the customer from the tariff it had cached, and that figure is
    now a fact, not a proposal. The server records what was charged, compares it
    with what it would have charged, and reports the difference rather than
    quietly rewriting either one.
    """

    #: When the customer actually paid.
    recorded_at = serializers.DateTimeField()
    #: What the till took, as a checksum against a queue corrupted in storage.
    charged_total = serializers.DecimalField(max_digits=13, decimal_places=2)

    def validate_recorded_at(self, value):
        if value > now() + timedelta(minutes=5):
            raise serializers.ValidationError(_("This sale is dated in the future."))
        if value < now() - MAX_OFFLINE_AGE:
            raise serializers.ValidationError(
                _("This sale is too old to be replayed automatically.")
            )
        return value


class TerminalStartSerializer(serializers.Serializer):
    """
    What the till sends to put a basket on the card reader.

    The same products-and-quantities payload as a checkout, and for the same
    reason: the server prices it. The only price it will read is a free
    amount's, which is the one figure the till is allowed to decide anywhere.
    """

    #: The key the sale will carry, minted once per attempt by the app. It is
    #: what makes a second tap find the payment already running rather than
    #: start a second one — SumUp's reader checkout has no such key of its own.
    idempotency_key = serializers.CharField(max_length=190)
    positions = CheckoutPositionSerializer(many=True, allow_empty=False, max_length=MAX_LINES)


class CheckoutSerializer(serializers.Serializer):
    """
    Note what this deliberately does *not* accept: a price.

    The till only ever names products and quantities. Prices are resolved
    server-side from the on-site tariff, so a tampered-with or simply outdated
    app cannot sell a 40 EUR ticket for 4 EUR.
    """

    #: Generated by the app before its first attempt and reused for every retry,
    #: so a flaky network or a double tap cannot sell the same tickets twice.
    #:
    #: Ten short of the column it is stored in, so that a transaction that also
    #: hands a deposit back can derive a second, distinct key from it for the
    #: journal row that records the payout. The app's own keys are a couple of
    #: dozen characters.
    idempotency_key = serializers.CharField(max_length=180, min_length=8)
    positions = serializers.ListField(
        child=CheckoutPositionSerializer(), allow_empty=False, max_length=MAX_LINES
    )
    payment_type = serializers.ChoiceField(choices=[c[0] for c in PosSale.PAYMENT_CHOICES])
    cash_given = serializers.DecimalField(
        max_digits=13, decimal_places=2, required=False, allow_null=True, default=None
    )
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )
    #: What the till showed the customer.
    #:
    #: The server is the price authority, which means it can silently charge
    #: something other than the amount the operator just read out — after a
    #: price change in the backend, or a catalogue refreshed mid-basket. Sending
    #: the expected figure turns that into a refusal before any money moves.
    expected_total = serializers.DecimalField(
        max_digits=13, decimal_places=2, required=False, allow_null=True, default=None
    )
    #: Present only for a sale replayed from a till that had no network.
    offline = OfflineSerializer(required=False, allow_null=True, default=None)

    def validate(self, data):
        offline = data.get("offline")
        priced = [p for p in data["positions"] if p.get("price") is not None]

        for position in data["positions"]:
            if position["refund"] and position["description"]:
                # Two different kinds of line, and the till never builds both
                # at once. Refusing here keeps the checkout from having to
                # decide which of the two it is looking at.
                raise serializers.ValidationError(
                    {"positions": [_("A deposit refund carries no free-text amount.")]}
                )
            if position["refund"] and position["variation"] is not None:
                raise serializers.ValidationError(
                    {"positions": [_("A deposit refund has no option to choose.")]}
                )
            if position["refund"] and (position["price"] or Decimal("0.00")) > 0:
                # Only reachable from a replayed queue, where the till does
                # send prices. A row whose kind says "money out" and whose
                # amount says "money in" is worse in an audit journal than an
                # odd figure: it contradicts itself.
                raise serializers.ValidationError(
                    {"positions": [_("A deposit refund cannot be a positive amount.")]}
                )

        if offline:
            # All or nothing: a partly priced basket means the queue is damaged,
            # and guessing the missing half is the one thing not to do with money.
            if len(priced) != len(data["positions"]):
                raise serializers.ValidationError(
                    {"positions": [_("Every line of an offline sale must carry the price charged.")]}
                )
            charged = sum(
                (p["price"] * p["count"] for p in data["positions"]), Decimal("0.00")
            )
            if charged != offline["charged_total"]:
                raise serializers.ValidationError(
                    {"offline": [_("The lines do not add up to the total charged.")]}
                )
            if data.get("expected_total") is not None:
                # It answers a question the till could not have asked offline.
                raise serializers.ValidationError(
                    {"expected_total": [_("An offline sale cannot carry an expected total.")]}
                )
        else:
            # Online, a price from the till is refused unless the line says
            # what it is for — which is what a free amount is, and the only
            # thing the server will price on the till's word. Everything else
            # names a product and gets the tariff. The checkout then checks
            # that the product really is the one the organiser set aside for
            # this; the rule here is only about the shape of the request.
            for position in data["positions"]:
                described = bool(position["description"].strip())
                if (position["price"] is not None) != described:
                    raise serializers.ValidationError(
                        {"positions": [_(
                            "Prices are decided by the server, except on a free-amount "
                            "line, which must carry both its amount and its reason."
                        )]}
                    )

        cash_given = data.get("cash_given")
        if data["payment_type"] == PosSale.PAYMENT_CASH:
            if cash_given is not None and cash_given < Decimal("0.00"):
                raise serializers.ValidationError(
                    {"cash_given": [_("The amount received cannot be negative.")]}
                )
        elif cash_given is not None:
            raise serializers.ValidationError(
                {"cash_given": [_("The amount received only applies to cash payments.")]}
            )
        return data


class CancelSerializer(serializers.Serializer):
    """
    Reverse one sale of this till, named by its journal sequence number.

    The order code is deliberately not what identifies it: the journal is the
    record that survives an order being purged, and its sequence number is what
    a printed report cites.
    """

    seq = serializers.IntegerField(min_value=1)
    #: Same replay protection as a sale: a timeout that in fact went through
    #: must not cancel twice, nor report a failure for work that was done.
    idempotency_key = serializers.CharField(max_length=190, min_length=8)
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )
    #: Optional for the operator, valuable to whoever reads the journal later.
    reason = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )


class DeviceStatusSerializer(serializers.Serializer):
    """
    What a till says about itself: the sales it has not managed to send yet.

    Its own account, on its own clock, and stored as such — the server has no
    way to count sales that never reached it, which is the whole point of
    asking. Strict all the same: a report that does not parse is an app bug
    worth a 400, not a number to show an organizer.
    """

    #: The column's own limit; a queue anywhere near it is a bug, not a night.
    pending_sales = serializers.IntegerField(min_value=0, max_value=2147483647)
    #: When the oldest unsent sale was rung up. ``null`` when nothing waits.
    oldest_pending_at = serializers.DateTimeField(allow_null=True, required=False, default=None)
    #: When the queue last went through, whole. ``null`` before it ever did.
    last_sync_at = serializers.DateTimeField(allow_null=True, required=False, default=None)
    version = serializers.CharField(max_length=64, allow_blank=True)


class DrawerCountSerializer(serializers.Serializer):
    """
    Cash counted into or out of a drawer: the float at opening, or a count.

    ``denominations`` is how it was counted when it was counted note by note,
    ``{"20.00": 3, "0.50": 4}``; the view checks that it names this currency's
    notes and coins and adds up to ``amount``.
    """

    idempotency_key = serializers.CharField(max_length=190, min_length=8)
    amount = serializers.DecimalField(max_digits=13, decimal_places=2, min_value=Decimal("0.00"))
    denominations = serializers.DictField(
        child=serializers.IntegerField(min_value=0, max_value=100000),
        required=False, default=dict,
    )
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )

    def validate_denominations(self, value):
        # Rows left at zero say nothing, and a key spelt "20" or "20.0" is
        # the same note as "20.00": normalised here, so the ledger keeps one
        # spelling and the view compares like with like.
        clean = {}
        for key, number in value.items():
            try:
                note = Decimal(str(key)).quantize(Decimal("0.01"))
            except ArithmeticError:
                raise serializers.ValidationError(_("“{value}” is not an amount.").format(value=key))
            if number:
                clean[str(note)] = clean.get(str(note), 0) + number
        return clean


class DrawerMovementSerializer(serializers.Serializer):
    """Money put into the open drawer, or taken out of it, and why."""

    idempotency_key = serializers.CharField(max_length=190, min_length=8)
    kind = serializers.ChoiceField(choices=["in", "out"])
    amount = serializers.DecimalField(max_digits=13, decimal_places=2, min_value=Decimal("0.01"))
    reason = serializers.CharField(max_length=190)
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )


class DrawerCloseSerializer(serializers.Serializer):
    """
    End the evening on the count just made.

    ``count_seq`` names that count. ``uncounted`` closes with no count at all,
    which the server only accepts for a drawer opened on an earlier day.
    """

    idempotency_key = serializers.CharField(max_length=190, min_length=8)
    count_seq = serializers.IntegerField(min_value=1, required=False, allow_null=True, default=None)
    uncounted = serializers.BooleanField(required=False, default=False)
    reason = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )
    cashier = serializers.CharField(
        max_length=190, required=False, allow_blank=True, default=""
    )

    def validate(self, data):
        if data["count_seq"] is None and not data["uncounted"]:
            raise serializers.ValidationError(
                {"count_seq": [_("Count the drawer before closing it.")]}
            )
        return data
